//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_Vinpearl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTHD
    {
        public string maHD { get; set; }
        public string maVe { get; set; }
        public Nullable<int> soLuong { get; set; }
        public Nullable<decimal> giaTien { get; set; }
    
        public virtual HOADON HOADON { get; set; }
        public virtual VE VE { get; set; }
    }
}
