//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_Vinpearl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DICHVU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DICHVU()
        {
            this.VE = new HashSet<VE>();
        }
    
        public string maDV { get; set; }
        public string tenDV { get; set; }
        public string moTa { get; set; }
        public string anh { get; set; }
        public string maLoaiDV { get; set; }
        public Nullable<double> xepLoai { get; set; }
        public string sdtDV { get; set; }
        public string diaChiDV { get; set; }
    
        public virtual LOAIDV LOAIDV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VE> VE { get; set; }
    }
}
