//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_Vinpearl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHANQUYEN
    {
        public string maChucNang { get; set; }
        public string maLoaiNV { get; set; }
        public string ghiChu { get; set; }
    
        public virtual CHUCNANG CHUCNANG { get; set; }
        public virtual LOAINV LOAINV { get; set; }
    }
}
