//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_Vinpearl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOCA
    {
        public string maCa { get; set; }
        public string maNV { get; set; }
        public Nullable<int> soCa1 { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
